apiVersion: v1
kind: Service
metadata:
  name: mssql-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mssql
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1433
