apiVersion: v1
kind: Service
metadata:
  name: oracle-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: oracle
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1521
