image:
  repository: mcr.microsoft.com/mssql/server
  tag: 2019-latest

securityContext:
  runAsUser: 10001
  fsGroup: 10001

env:
  ACCEPT_EULA: "Y"
  SA_PASSWORD: "YourStrong!Passw0rd"
  MSSQL_PID: "Developer"

persistence:
  storageClass: "standard"
  size: 8Gi

service:
  type: ClusterIP
  port: 1433
